/**
 * Phase 7 — Route Enumeration Auth Coverage Test
 *
 * Proves: every registered Express route returns 401 without a JWT,
 * unless it is in the UNAUTHENTICATED_ALLOWLIST (single source of truth).
 *
 * Fails CI if any route is reachable without authentication.
 */
import { app } from "../src/app";
import { UNAUTHENTICATED_ALLOWLIST } from "../src/auth/authMiddleware";
import { requestApp } from "./test_helpers";

type RouteEntry = { method: string; path: string };

/**
 * Extract all registered routes from the Express app router stack.
 * Walks app._router.stack to find route layers.
 */
const extractRoutes = (): RouteEntry[] => {
  const router = (app as any)._router;
  if (!router || !router.stack) {
    throw new Error("Express router stack not found — cannot enumerate routes");
  }

  const routes: RouteEntry[] = [];

  for (const layer of router.stack) {
    if (layer.route) {
      const routePath: string = layer.route.path;
      const methods: Record<string, boolean> = layer.route.methods;
      for (const method of Object.keys(methods)) {
        if (methods[method]) {
          routes.push({ method: method.toUpperCase(), path: routePath });
        }
      }
    }
  }

  return routes;
};

/**
 * Replace Express path parameters with synthetic values.
 * Auth middleware runs before route matching, so the actual value doesn't matter.
 */
const substituteParams = (path: string): string => {
  return path.replace(/:([a-zA-Z_]+)/g, "test-param-$1");
};

/**
 * Check if a route is in the allowlist.
 */
const isAllowlisted = (method: string, path: string): boolean => {
  return UNAUTHENTICATED_ALLOWLIST.some(
    (entry) => entry.method === method && entry.path === path
  );
};

describe("Route enumeration — auth coverage", () => {
  let allRoutes: RouteEntry[];

  beforeAll(() => {
    allRoutes = extractRoutes();
  });

  it("Express router stack is accessible", () => {
    expect((app as any)._router).toBeDefined();
    expect((app as any)._router.stack).toBeDefined();
  });

  it("No sub-routers exist (all routes are directly registered)", () => {
    const router = (app as any)._router;
    const subRouters = router.stack.filter(
      (layer: any) => layer.name === "router" && !layer.route
    );
    expect(subRouters.length).toBe(0);
  });

  it("Route enumeration discovers registered routes", () => {
    expect(allRoutes.length).toBeGreaterThan(0);
    // Log for reviewer visibility
    console.log(`Discovered ${allRoutes.length} routes:`);
    allRoutes.forEach((r) => console.log(`  ${r.method} ${r.path}`));
  });

  it("UNAUTHENTICATED_ALLOWLIST contains exactly 2 entries", () => {
    expect(UNAUTHENTICATED_ALLOWLIST.length).toBe(2);
    expect(UNAUTHENTICATED_ALLOWLIST).toContainEqual({ method: "GET", path: "/health" });
    expect(UNAUTHENTICATED_ALLOWLIST).toContainEqual({ method: "POST", path: "/auth/login" });
  });

  it("Every non-allowlisted route returns 401 without a JWT", async () => {
    const failures: string[] = [];

    for (const route of allRoutes) {
      if (isAllowlisted(route.method, route.path)) {
        continue;
      }

      // Skip HEAD (auto-generated by Express for GET routes)
      if (route.method === "HEAD") {
        continue;
      }

      const testPath = substituteParams(route.path);
      const response = await requestApp(app, {
        method: route.method as any,
        path: testPath,
        // No auth headers — testing unauthenticated access
      });

      if (response.status !== 401) {
        failures.push(
          `${route.method} ${route.path} → ${response.status} (expected 401)`
        );
      }
    }

    if (failures.length > 0) {
      console.error("AUTH COVERAGE FAILURES:");
      failures.forEach((f) => console.error(`  ${f}`));
    }
    expect(failures).toEqual([]);
  });

  it("Allowlisted routes are accessible without auth", async () => {
    // GET /health should return 200
    const healthRes = await requestApp(app, {
      method: "GET",
      path: "/health",
    });
    expect(healthRes.status).toBe(200);

    // POST /auth/login should return 401 (bad credentials) not 401 (no auth)
    const loginRes = await requestApp(app, {
      method: "POST",
      path: "/auth/login",
      body: { username: "invalid", password: "invalid" },
    });
    // 401 from invalid credentials is expected — the point is it's not blocked by authMiddleware
    expect(loginRes.status).toBe(401);
    expect((loginRes.body as any).error).toBe("Invalid credentials");
  });
});
