#!/usr/bin/env node
// AI Value demo seeder.
//
// Loads the committed customer-support example chain into ai_value_objects
// through the governed /api/v1/ai-value API so the in-app Value Journey,
// Workspace, and executive readout render a fully populated engagement from a
// clean checkout. Every object is validated server-side (fail-closed); this
// script never writes the database directly.
//
// Flow:
//   1. PUT the upstream inputs (engagement, fluency_baseline, blueprint,
//      metrics_library, outcome_evidence_export).
//   2. POST the outcome-evidence /review ACCEPT step (reviewer-only).
//   3. POST /value-chain/run to generate + persist the derived objects
//      (value_scenario, evidence_readiness, claim_boundary, executive_packet).
//
// Requires a running backend with header auth enabled (DEV_HEADER_AUTH=true,
// which `npm run dev --workspace backend` sets automatically).
//
// Env / flags:
//   --base   | AI_VALUE_API_BASE   default http://localhost:4000
//   --org    | AI_VALUE_ORG        default org-northstar-enterprise
//   --role   | AI_VALUE_ROLE       default ADMIN
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const EXAMPLES = "docs/contracts/ai-value-intelligence/examples";

// Seeded in dependency order. The four derived stage objects (value_scenario,
// evidence_readiness, claim_boundary, executive_packet) are NOT listed here -
// they are generated by the value-chain run below.
const INPUTS = [
  { file: "customer-support-engagement.json", type: "engagement", idField: "engagement_id" },
  { file: "customer-support-fluency-baseline.json", type: "fluency_baseline", idField: "baseline_id" },
  { file: "customer-support-blueprint.json", type: "blueprint", idField: "blueprint_id" },
  { file: "customer-support-metrics-library.json", type: "metrics_library", idField: "library_id" },
  {
    file: "customer-support-outcome-evidence-export.json",
    type: "outcome_evidence_export",
    idField: "export_id"
  }
];

function parseArgs(argv) {
  const args = {
    base: process.env.AI_VALUE_API_BASE ?? "http://localhost:4000",
    org: process.env.AI_VALUE_ORG ?? "org-northstar-enterprise",
    role: process.env.AI_VALUE_ROLE ?? "ADMIN"
  };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--base") args.base = argv[++i];
    else if (arg === "--org") args.org = argv[++i];
    else if (arg === "--role") args.role = argv[++i];
    else if (arg === "--help" || arg === "-h") {
      console.log(
        "Usage: node scripts/seed_ai_value_demo.mjs [--base http://localhost:4000] [--org org-northstar-enterprise] [--role ADMIN]"
      );
      process.exit(0);
    } else {
      throw new Error(`Unknown argument: ${arg}`);
    }
  }
  args.base = args.base.replace(/\/+$/, "");
  return args;
}

function readJson(file) {
  return JSON.parse(readFileSync(resolve(process.cwd(), EXAMPLES, file), "utf8"));
}

async function api(args, method, path, body) {
  const response = await fetch(`${args.base}${path}`, {
    method,
    headers: {
      "content-type": "application/json",
      "x-role": args.role,
      "x-org-id": args.org
    },
    body: body === undefined ? undefined : JSON.stringify(body)
  });
  let payload = null;
  try {
    payload = await response.json();
  } catch {
    payload = null;
  }
  return { status: response.status, ok: response.ok, payload };
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  console.log(`Seeding AI value demo into ${args.base} for org ${args.org} (role ${args.role})`);

  const ids = {};

  for (const { file, type, idField } of INPUTS) {
    const payload = readJson(file);
    // Land every object in the active org so org scoping stays consistent
    // (the API enforces this for outcome_evidence_export and ignores it otherwise).
    if (Object.prototype.hasOwnProperty.call(payload, "org_id")) {
      payload.org_id = args.org;
    }
    const objectId = String(payload[idField]);
    ids[type] = objectId;

    const res = await api(args, "PUT", `/api/v1/ai-value/objects/${type}/${encodeURIComponent(objectId)}`, payload);
    if (res.ok) {
      console.log(`  OK ${type} ${objectId}`);
    } else if (type === "outcome_evidence_export" && res.status === 409 && res.payload?.reason === "TERMINAL_REVIEW_STATE") {
      console.log(`  - ${type} ${objectId} already reviewed (skipping re-upload)`);
    } else {
      fail(`PUT ${type} ${objectId}`, res);
    }
  }

  // Accept the customer outcome evidence so the readout can attach it. Tolerate
  // the case where a prior run already accepted it (terminal state).
  const exportId = ids.outcome_evidence_export;
  const review = await api(
    args,
    "POST",
    `/api/v1/ai-value/objects/outcome_evidence_export/${encodeURIComponent(exportId)}/review`,
    { decision: "ACCEPTED" }
  );
  if (review.ok) {
    console.log(`  OK accepted outcome evidence ${exportId} (${review.payload?.review_state ?? "ACCEPTED"})`);
  } else if (review.status === 409) {
    console.log(`  - outcome evidence ${exportId} already in a terminal review state`);
  } else {
    fail(`review ${exportId}`, review);
  }

  // Generate + persist the derived chain (scenario, readiness, claim_boundary,
  // executive_packet) by running the value chain over the seeded inputs.
  const run = await api(args, "POST", "/api/v1/ai-value/value-chain/run", {
    blueprint_id: ids.blueprint,
    metrics_library_id: ids.metrics_library,
    engagement_id: ids.engagement,
    fluency_baseline_id: ids.fluency_baseline,
    outcome_evidence_export_id: ids.outcome_evidence_export
  });
  if (!run.ok) fail("value-chain/run", run);

  const decision = run.payload?.run?.decision ?? "UNKNOWN";
  const persisted = run.payload?.persisted ?? [];
  console.log(`  OK value chain ran - decision ${decision}, persisted ${persisted.length} derived object(s):`);
  for (const obj of persisted) console.log(`      - ${obj.object_type} ${obj.object_id}`);

  console.log("\nDone. Set the browser org to this value and open /ai-value:");
  console.log(`  localStorage.setItem("orgId", "${args.org}")  (or sign in via /login)`);
}

function fail(step, res) {
  console.error(`\nx ${step} failed: HTTP ${res.status}`);
  if (res.payload) console.error(JSON.stringify(res.payload, null, 2));
  if (res.status === 0 || res.status === undefined) {
    console.error("Is the backend running with DEV_HEADER_AUTH=true? (npm run dev --workspace backend)");
  }
  process.exit(1);
}

main().catch((error) => {
  console.error(`\nx Seeder error: ${error.message}`);
  console.error("Is the backend reachable? (npm run dev --workspace backend, default http://localhost:4000)");
  process.exit(1);
});
